#define SCANCODE_ESC            0x01
#define SCANCODE_F1             0x3b
#define SCANCODE_F2             0x3c
#define SCANCODE_F3             0x3d
#define SCANCODE_F4             0x3e
#define SCANCODE_F5             0x3f
#define SCANCODE_F6             0x40
#define SCANCODE_F7             0x41
#define SCANCODE_F8             0x42
#define SCANCODE_F9             0x43
#define SCANCODE_F10            0x44
#define SCANCODE_F11            0x57
#define SCANCODE_F12            0x58
#define SCANCODE_Ctrl           0x1d
#define SCANCODE_Space          0x39

#define SCANCODE_1              0x02
#define SCANCODE_2              0x03
#define SCANCODE_3              0x04
#define SCANCODE_4              0x05
#define SCANCODE_5              0x06
#define SCANCODE_6              0x07
#define SCANCODE_7              0x08
#define SCANCODE_8              0x09
#define SCANCODE_9              0x0a
#define SCANCODE_0              0x0b

#define SCANCODE_A              0x1e
#define SCANCODE_B              0x30
#define SCANCODE_C              0x2e
#define SCANCODE_D              0x20
#define SCANCODE_E              0x12
#define SCANCODE_F              0x21
#define SCANCODE_G              0x22
#define SCANCODE_H              0x23
#define SCANCODE_I              0x17
#define SCANCODE_J              0x24
#define SCANCODE_K              0x25
#define SCANCODE_L              0x26
#define SCANCODE_M              0x32
#define SCANCODE_N              0x31
#define SCANCODE_O              0x18
#define SCANCODE_P              0x19
#define SCANCODE_Q              0x10
#define SCANCODE_R              0x13
#define SCANCODE_S              0x1f
#define SCANCODE_T              0x14
#define SCANCODE_U              0x16
#define SCANCODE_V              0x2f
#define SCANCODE_W              0x11
#define SCANCODE_X              0x2d
#define SCANCODE_Y              0x15
#define SCANCODE_Z              0x2c

#define SCANCODE_Shift          0x2a
#define SCANCODE_Alt            0x38